---
language: php

cache:
  directories:
  - $HOME/.composer/cache/files

php:
- nightly
- 7.2
- 7.1
- 7.0

env:
  global:
  - PATH=$TRAVIS_BUILD_DIR/bin::$PATH

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly

before_install:
- go get -u github.com/jingweno/ccat
# Disabling Xdebug - Debugger and Profiler Tool for PHP
- php -r "print_r(get_loaded_extensions(TRUE));";
  if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
    cat ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini;
    install --directory ~/.phpenv/versions/$(phpenv version-name)/etc/on-demand;
    mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/.phpenv/versions/$(phpenv version-name)/etc/on-demand;
    php -r "print_r(get_loaded_extensions(TRUE));";
  fi

install:
- composer install
- command -v console
# - composer initialize

script: true

after_script:
- ls --color
- ls --recursive --color bin

- composer show --latest
- $GOPATH/bin/ccat composer.json

- composer console
- composer console -- list doctrine --ansi
- composer console -- help doctrine:database:create --ansi
- composer console -- help make:entity --ansi

- $GOPATH/bin/ccat config/packages/doctrine.yaml

- composer require --no-scripts sensiolabs/security-checker
- composer security:check -- --end-point=http://security.sensiolabs.org/check_lock --ansi
- $GOPATH/bin/ccat composer.json
